[tool.towncrier]
package = "RPD"
package_dir = "rpd"
directory = "changes"
filename = "CHANGELOG.md"
issue_format = "[#{issue}](https://github.com/rpd-py/rpd/issues/{issue})"
type = [
    { name = "Breaking Changes",            directory = "breaking",     showcontent = true },
    { name = "Deprecation",                 directory = "deprecation",  showcontent = true },
    { name = "Features",                    directory = "feature",      showcontent = true },
    { name = "Bugfixes",                    directory = "bugfix",       showcontent = true },
    { name = "Documentation",               directory = "doc",          showcontent = true },
]
